### ISSUE TITLE
template naming scheme discrepancy

### ISSUE THREAD

**Issue by jclauneuro** [afids/afids-protocol#3]
There is discrepancy between the naming schemes used on the afids website and that used for the afids-validator. The naming conventions should be consolidated to avoid confusion.

Migrating to the BIDS and templateflow framework for describing templates will likely be a good solution.

**Comment by greydongilmore** [comment]
The protocol website template naming has been updated to match the validator website for now (https://github.com/afids/afids-protocol/pull/15#issue-464253919)

**Comment by greydongilmore** [comment]
will close for now, discussion of BIDs template naming will be planned for the future
